FROM node:18-alpine as build-stage

WORKDIR /app

COPY ktv-client/package*.json ./ktv-client/
RUN cd ktv-client && npm install

COPY ktv-client/. .

RUN cd ktv-client && npm run build

# 生产阶段
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/ktv-client/dist /usr/share/nginx/html/client
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]