FROM node:18-alpine as build-stage

WORKDIR /app

COPY ktv-admin/package*.json ./ktv-admin/
RUN cd ktv-admin && npm install

COPY ktv-admin/. .

RUN cd ktv-admin && npm run build

# 生产阶段
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/ktv-admin/dist /usr/share/nginx/html/admin
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]